name: Deno Test

on:
  push:
    branches: ["master"]
    paths:
      - "the-chat/server/**"
  pull_request:
    branches: ["master"]
    paths:
      - "the-chat/server/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.34, 1.35]

    defaults:
      run:
        working-directory: the-chat/server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2dfa3283
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-cache-${{ matrix.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --allow-all
